### PR TITLE
wasapi: Allow both threading models and switch the default to STA

### LINKED ISSUE #59: Issue with IAudioClient::Initialize?
On this page: https://msdn.microsoft.com/en-us/library/windows/desktop/dd370875%28v=vs.85%29.aspx

> Note  In Windows 8, the first use of IAudioClient to access the audio device should be on the STA thread. Calls from an MTA thread may result in undefined behavior.

cpal initializes COM in MTA mode.

### LINKED ISSUE #530: Import examples in Unity
Hello all,

I'm using MSVC rust on Windows.

Just trying to make a beep from a cpal plugin in Unity.
I just wrapped the beep example into a simple function, made a dylib dll that I loaded in Unity.
The example works fine from a simple main binary written in Rust.
But it crashes in Unity.

```
#[no_mangle]
pub extern fn sound() {
    let host = cpal::default_host();

    let device = host
        .default_output_device()
        .expect("failed to find a default output device");
    let config = device.default_output_config().unwrap();

    match config.sample_format() {
        cpal::SampleFormat::F32 => run::<f32>(&device, &config.into()).unwrap(),
        cpal::SampleFormat::I16 => run::<i16>(&device, &config.into()).unwrap(),
        cpal::SampleFormat::U16 => run::<u16>(&device, &config.into()).unwrap(),
    }
}
```

It seems that it crashes when it tries to load the default output device. I'm not really sure how to break somewhere, or a way to check what is really, but doing useless stuff before seems OK, until loading the device.

Did someone already managed to do that ? I'm not sure if we need to specify something when loading a dll in Unity, especially for sound (thread etc,)

Thanks !

### LINKED ISSUE #538: Panic when running enumerate.rs example
Hello,

I get the following error when I run the enumerate.rs example:

Supported hosts:
  [Asio, Wasapi]
Available hosts:
  [Asio, Wasapi]
ASIO
  Default Input Device:
    Some("ASIO TonePort UX2")
  Default Output Device:
    Some("ASIO TonePort UX2")
  Devices:
  1. "ASIO TonePort UX2"
    Default input stream config:
      SupportedStreamConfig { channels: 4, sample_rate: SampleRate(44100), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
    All supported input stream configs:
      1.1. SupportedStreamConfigRange { channels: 1, min_sample_rate: SampleRate(44100), max_sample_rate: SampleRate(44100), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.2. SupportedStreamConfigRange { channels: 2, min_sample_rate: SampleRate(44100), max_sample_rate: SampleRate(44100), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.3. SupportedStreamConfigRange { channels: 3, min_sample_rate: SampleRate(44100), max_sample_rate: SampleRate(44100), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.4. SupportedStreamConfigRange { channels: 4, min_sample_rate: SampleRate(44100), max_sample_rate: SampleRate(44100), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.5. SupportedStreamConfigRange { channels: 1, min_sample_rate: SampleRate(48000), max_sample_rate: SampleRate(48000), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.6. SupportedStreamConfigRange { channels: 2, min_sample_rate: SampleRate(48000), max_sample_rate: SampleRate(48000), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.7. SupportedStreamConfigRange { channels: 3, min_sample_rate: SampleRate(48000), max_sample_rate: SampleRate(48000), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.8. SupportedStreamConfigRange { channels: 4, min_sample_rate: SampleRate(48000), max_sample_rate: SampleRate(48000), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.9. SupportedStreamConfigRange { channels: 1, min_sample_rate: SampleRate(88200), max_sample_rate: SampleRate(88200), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.10. SupportedStreamConfigRange { channels: 2, min_sample_rate: SampleRate(88200), max_sample_rate: SampleRate(88200), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.11. SupportedStreamConfigRange { channels: 3, min_sample_rate: SampleRate(88200), max_sample_rate: SampleRate(88200), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.12. SupportedStreamConfigRange { channels: 4, min_sample_rate: SampleRate(88200), max_sample_rate: SampleRate(88200), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.13. SupportedStreamConfigRange { channels: 1, min_sample_rate: SampleRate(96000), max_sample_rate: SampleRate(96000), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.14. SupportedStreamConfigRange { channels: 2, min_sample_rate: SampleRate(96000), max_sample_rate: SampleRate(96000), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.15. SupportedStreamConfigRange { channels: 3, min_sample_rate: SampleRate(96000), max_sample_rate: SampleRate(96000), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.16. SupportedStreamConfigRange { channels: 4, min_sample_rate: SampleRate(96000), max_sample_rate: SampleRate(96000), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
    Default output stream config:
      SupportedStreamConfig { channels: 2, sample_rate: SampleRate(44100), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
    All supported output stream configs:
      1.1. SupportedStreamConfigRange { channels: 1, min_sample_rate: SampleRate(44100), max_sample_rate: SampleRate(44100), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.2. SupportedStreamConfigRange { channels: 2, min_sample_rate: SampleRate(44100), max_sample_rate: SampleRate(44100), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.3. SupportedStreamConfigRange { channels: 1, min_sample_rate: SampleRate(48000), max_sample_rate: SampleRate(48000), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.4. SupportedStreamConfigRange { channels: 2, min_sample_rate: SampleRate(48000), max_sample_rate: SampleRate(48000), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.5. SupportedStreamConfigRange { channels: 1, min_sample_rate: SampleRate(88200), max_sample_rate: SampleRate(88200), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.6. SupportedStreamConfigRange { channels: 2, min_sample_rate: SampleRate(88200), max_sample_rate: SampleRate(88200), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.7. SupportedStreamConfigRange { channels: 1, min_sample_rate: SampleRate(96000), max_sample_rate: SampleRate(96000), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
      1.8. SupportedStreamConfigRange { channels: 2, min_sample_rate: SampleRate(96000), max_sample_rate: SampleRate(96000), buffer_size: Range { min: 128, max: 4096 }, sample_format: I16 }
WASAPI
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: -2147417850, kind: Other, message: "Impossible de modifier le mode thread une fois qu’il a été fixé." }', C:\Users\downfall85\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.13.1\src\host\wasapi\com.rs:13:77
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\std\src\panicking.rs:495
   1: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\core\src\panicking.rs:92
   2: core::option::expect_none_failed
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\core\src\option.rs:1268
   3: core::result::Result<tuple<>, std::io::error::Error>::unwrap<tuple<>,std::io::error::Error>
             at C:\Users\downfall85\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\result.rs:973
   4: cpal::host::wasapi::com::COM_INITIALIZED::__init
             at C:\Users\downfall85\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.13.1\src\host\wasapi\com.rs:13
   5: core::ops::function::FnOnce::call_once<fn() -> cpal::host::wasapi::com::ComInitialized,tuple<>>
             at C:\Users\downfall85\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
   6: std::thread::local::lazy::LazyKeyInner<cpal::host::wasapi::com::ComInitialized>::initialize<cpal::host::wasapi::com::ComInitialized,fn() -> cpal::host::wasapi::com::ComInitialized>
             at C:\Users\downfall85\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:304
   7: std::thread::local::fast::Key<cpal::host::wasapi::com::ComInitialized>::try_initialize<cpal::host::wasapi::com::ComInitialized,fn() -> cpal::host::wasapi::com::ComInitialized>
             at C:\Users\downfall85\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:473
   8: std::thread::local::fast::Key<cpal::host::wasapi::com::ComInitialized>::get<cpal::host::wasapi::com::ComInitialized,fn() -> cpal::host::wasapi::com::ComInitialized>
             at C:\Users\downfall85\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:456
   9: cpal::host::wasapi::com::COM_INITIALIZED::__getit
             at C:\Users\downfall85\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:183
  10: std::thread::local::LocalKey<cpal::host::wasapi::com::ComInitialized>::try_with<cpal::host::wasapi::com::ComInitialized,closure-0,tuple<>>
             at C:\Users\downfall85\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:271
  11: std::thread::local::LocalKey<cpal::host::wasapi::com::ComInitialized>::with<cpal::host::wasapi::com::ComInitialized,closure-0,tuple<>>
             at C:\Users\downfall85\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:248
  12: cpal::host::wasapi::com::com_initialized
             at C:\Users\downfall85\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.13.1\src\host\wasapi\com.rs:34
  13: core::ops::function::FnOnce::call_once<fn() -> cpal::host::wasapi::device::Enumerator,tuple<>>
             at C:\Users\downfall85\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
  14: lazy_static::lazy::{{impl}}::get::{{closure}}<cpal::host::wasapi::device::Enumerator,fn() -> cpal::host::wasapi::device::Enumerator>
             at C:\Users\downfall85\.cargo\registry\src\github.com-1ecc6299db9ec823\lazy_static-1.4.0\src\inline_lazy.rs:31
  15: std::sync::once::{{impl}}::call_once::{{closure}}<closure-0>
             at C:\Users\downfall85\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sync\once.rs:261
  16: std::sync::once::Once::call_inner
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\std\src\sync\once.rs:419
  17: std::sync::once::Once::call_once<closure-0>
             at C:\Users\downfall85\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sync\once.rs:261
  18: lazy_static::lazy::Lazy<cpal::host::wasapi::device::Enumerator>::get
             at C:\Users\downfall85\.cargo\registry\src\github.com-1ecc6299db9ec823\lazy_static-1.4.0\src\inline_lazy.rs:30
  19: cpal::host::wasapi::device::{{impl}}::deref::__stability
             at C:\Users\downfall85\.cargo\registry\src\github.com-1ecc6299db9ec823\lazy_static-1.4.0\src\lib.rs:142
  20: cpal::host::wasapi::device::{{impl}}::deref
             at C:\Users\downfall85\.cargo\registry\src\github.com-1ecc6299db9ec823\lazy_static-1.4.0\src\lib.rs:144
  21: cpal::host::wasapi::device::default_device
             at C:\Users\downfall85\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.13.1\src\host\wasapi\device.rs:1182
  22: cpal::host::wasapi::device::default_input_device
             at C:\Users\downfall85\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.13.1\src\host\wasapi\device.rs:1191
  23: cpal::host::wasapi::{{impl}}::default_input_device
             at C:\Users\downfall85\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.13.1\src\host\wasapi\mod.rs:46
  24: cpal::platform::platform_impl::{{impl}}::default_input_device
             at C:\Users\downfall85\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.13.1\src\platform\mod.rs:333
  25: pitch_shifter_rt::main
             at .\src\main.rs:15
  26: core::ops::function::FnOnce::call_once<fn() -> core::result::Result<tuple<>, anyhow::Error>,tuple<>>
             at C:\Users\downfall85\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\pitch_shifter_rt.exe` (exit code: 101)

From the file src\host\wasapi\com.rs:13:77; it seems hat there is already a COM library initialized in single-threaded mode and it's certainly by the ASIO code

thread_local!(static COM_INITIALIZED: ComInitialized = {
    unsafe {
        // this call can fail if another library initialized COM in single-threaded mode
        // handling this situation properly would make the API more annoying, so we just don't care
        **check_result(CoInitializeEx(ptr::null_mut(), COINIT_MULTITHREADED)).unwrap(); <- line 13**
        ComInitialized(ptr::null_mut())
    }
});

Os : Windows 10 64bits
Cpal version : 0.13.1 (build with asio)

### LINKED ISSUE #572: Single threaded COM initialization on Windows
I should preface this with that I don't really know what I'm talking about here, I'm just trying to solve an issue that I'm running into in the Bevy game engine, so I'm looking around to try finding possible solutions. So please correct me if I'm wrong anywhere. :)

In Bevy there are some issues with COM and it being single-threaded or multi-threaded. Drag and drop in Bevy uses single-threaded COM (I think it needs to?), and cpal uses multi-threaded. This causes issues because it seems like COM can only be initialized as single-threaded or multi-threaded for each thread, otherwise it crashes.

I don't know if or how this can be solved in Bevy, but one gracious Bevy community member says it worked for them when they modified the cpal source so it initializes in single threaded mode.

My question is: would it make sense as a feature in cpal to enable the ability to initialize it in single threaded mode if the user wants?

Here's one of the places where we've talked about this: https://github.com/bevyengine/bevy/issues/2096

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
COM can prevent undefined behavior in either concurrency model by
performing marshaling when necessary. As a result, CoInitializeEx can be
called with either concurrency model, and in this case STA provides better
compatibility with other code requiring STA, e.g. ASIO backend or winit
drag-and-drop.

To dive into the detail, the entry point of WASAPI, MMDeviceEnumerator, is
registered with "both" threading model, which means that COM objects are
created with whatever the thread's concurrency model is set to. This raises
the concern that when STA is used, marshaling might make audio buffer
operations block on the main thread, breaking continuous audio processing.
However, the implementation actually uses free-threaded marshaller for
interfaces dealing with buffer operations, which effectively bypasses COM's
compatibility marshaling behavior and perform any API calls on the caller's
thread instead. Therefore, the interfaces would operate just fine on either
concurrency model.

For more details on COM's threading model, see [1].

[1] https://thrysoee.dk/InsideCOM+/ch04d.htm

Co-Authored-By: Henrik Rydgård <hrydgard@gmail.com>

Close #59
Close #348
Close #504
Close #530
Close #538
Close #572

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
cc @hrydgard @JoshuaBatty

**Review by hrydgard — APPROVED** [review]

**Comment by Ralith** [comment]
Thanks for doing all that research and sorting this out, this is awesome!

File: src/host/wasapi/com.rs [hunk 1]
```diff
@@ -1,30 +1,50 @@
...
 });
 
 /// RAII object that guards the fact that COM is initialized.
 ///
 // We store a raw pointer because it's the only way at the moment to remove `Send`/`Sync` from the
 // object.
-struct ComInitialized(*mut ());
+struct ComInitialized {
+    result: HRESULT,
+    _ptr: *mut (),
```
Comment (maroider) [inline src/host/wasapi/com.rs]:
```suggestion
    _marker: PhantomData<*mut ()>,
```

Using `PhantomData<*mut T>` avoids the need to store a pointer while still removing `Send`/`Sync`.

File: src/host/wasapi/com.rs [hunk 2]
```diff
@@ -1,30 +1,50 @@
...
 thread_local!(static COM_INITIALIZED: ComInitialized = {
     unsafe {
-        // this call can fail if another library initialized COM in single-threaded mode
-        // handling this situation properly would make the API more annoying, so we just don't care
-        check_result(CoInitializeEx(ptr::null_mut(), COINIT_MULTITHREADED)).unwrap();
-        ComInitialized(ptr::null_mut())
+        // Try to initialize COM with STA by default to avoid compatibility issues with the ASIO
+        // backend (where CoInitialize() is called by the ASIO SDK) or winit (where drag and drop
+        // requires STA).
+        // this call can fail with RPC_E_CHANGED_MODE if another library initialized COM with MTA.
```
Comment (maroider) [inline src/host/wasapi/com.rs]:
```suggestion
        // This call can fail with RPC_E_CHANGED_MODE if another library initialized COM with MTA.
```
nit: capitalization

**Review by maroider — CHANGES_REQUESTED** [review]
Echoing what @Ralith said: Thanks for fixing this long-standing issue!

I think this PR also fixes #530 and #572.

**Comment by ishitatsuyuki** [comment]
Thanks @maroider for the suggested changes!

**Review by est31 — APPROVED** [review]
Thanks!

**Comment by est31** [comment]
This is a big one. i think it warrants a new release, don't you think?

**Comment by ishitatsuyuki** [comment]
Yeah, let's have a release!

**Comment by ishitatsuyuki** [comment]
@est31 I don't have publish perms on crates.io, would you mind doing the release? (just a friendly reminder)

**Comment by est31** [comment]
@ishitatsuyuki I think it should be enough to file a PR that increases the version. That will trigger the auto publish machinery.

**Comment by ishitatsuyuki** [comment]
Got it, will do that tomorrow unless someone beat me to it.

**Comment by est31** [comment]
0.13.4 is out: #598

**Comment by danwilhelm** [comment]
@ishitatsuyuki Thanks for thoroughly researching this issue!

**Comment by JoshuaBatty** [comment]
Thanks @ishitatsuyuki for doing this. Very much appreciated!
